/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Nat,
  'sqft' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'address' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'clientName' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func([Property], [IDL.Nat], []),
  'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'removeProperty' : IDL.Func([IDL.Nat], [], []),
  'removeTestimonial' : IDL.Func([IDL.Nat], [], []),
  'submitContact' : IDL.Func([ContactSubmission], [IDL.Nat], []),
  'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
  'updateTestimonial' : IDL.Func([IDL.Nat, Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Nat,
    'sqft' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'address' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'clientName' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func([Property], [IDL.Nat], []),
    'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'removeProperty' : IDL.Func([IDL.Nat], [], []),
    'removeTestimonial' : IDL.Func([IDL.Nat], [], []),
    'submitContact' : IDL.Func([ContactSubmission], [IDL.Nat], []),
    'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
    'updateTestimonial' : IDL.Func([IDL.Nat, Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };